source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '10.0'

use_frameworks!:linkage => :static
use_modular_headers!

target 'ArgoKitDemo' do
  pod 'ArgoKit', :path=>'../'
  pod 'ArgoKitPreview', :path=>'../', :link_style => 'weak'
  pod 'ArgoKitComponent', :path =>'../'

#  pod 'ArgoUI/Kit/AnimationCPP', :git => 'https://github.com/mmdongxin/MLN', :branch => 'dev_iOS_dx_temp'
#  pod 'ArgoUI/Kit/AnimationKit', :path => '../../MLN/ArgoUI.podspec'
# :modular_headers => true
end

